GET http://localhost:4000/


###
GET http://192.168.1.101:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtNjFrMHVxZjAwMDJhajg4aHdmcmdyZXoiLCJlbWFpbCI6ImRpbWFzIiwiaWF0IjoxNzM3MTY2NTc4LCJleHAiOjE3MzcxNzAxNzh9.wJPbACrs0LlA6mXuzqrF4QjLP0kaBQv1SA_Ddu9CFIw

### 
POST  http://192.168.1.101:4000/login
Content-Type: application/json

{
    "emailUser" : "dimas",
    "pass" : "132456789"
}


###
POST http://192.168.1.101:4000/user-add
Content-Type: application/json

{
    "email" : "dfgdsr@gmail.com",
    "name" : "234234",
    "password" : "123456"
}


### 
GET http://localhost:4000/get-user/alice@prisma.io


###
PATCH http://localhost:4000/update-user/alice@prisma.io
Content-Type: application/json

{
    "name" : "324",
    "password" : "123456234234"
}

###
DELETE http://localhost:4000/delete-user/dfgdsr@gmail.com

